version: '3'

services:
  lambda:
    build: .
    environment:
      - PYTHONPATH=/var/task/src:/opt/lib
      - PATH=/opt/bin
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-2
      - AWS_EXECUTION_ENV=YES
    volumes:
      - ./src/:/var/task/src/
